version: "3"
services:
  udagram-reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: jwizerd/reverseproxy:v1.5
  udagram-api-user:
    build:
      context: ./udagram-api-user
    image: jwizerd/udagram-api-user:v1.5
  udagram-api-feed:
    build:
      context: ./udagram-api-feed
    image: jwizerd/udagram-api-feed:v1.5
  udagram-frontend:
    build:
      context: ./udagram-frontend
    image: jwizerd/udagram-frontend:v1.5